services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 1323:1323
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - api

volumes:
  db:
